
[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "picar-x"
authors = [
  { name="sunfounder", email="service@sunfounder.com" },
  { name="Tobin McD", email="138074176+tobinmcd@users.noreply.github.com" },
]
description = "Picar-X Projects"
readme = "README.md"
requires-python = ">=3.13"
keywords = ["picar-x", "sunfounder"]
dynamic = ["version"]

dependencies = [
    "fastapi[standard]>=0.121.2",
    "gpiozero>=2.0.1",
    "keyboard>=0.13.5",
    "uvicorn>=0.22.0",
]

[dependency-groups]
robot = [
    "robot-hat @ git+https://github.com/sunfounder/robot-hat.git",
    "vilib @ git+https://github.com/sunfounder/vilib.git",
    "smbus2>=0.6.0",
    "pyaudio>=0.2.14",
    "aiortc>=1.14.0",
]

[project.scripts]
picarx-serve = "gerg_driver.server:main"

[tool.poe.tasks]
serve = "picarx-serve"
robot-sync = "uv sync --group robot"


[project.urls]
Repository = "https://github.com/tobinmcd/picar-x"

[tool.setuptools]
packages = [
  "picarx",
  "gerg_driver",
]

[tool.setuptools.package-data]
"gerg_driver" = ["templates/*.html"]

[tool.setuptools.dynamic]
version = {attr = "picarx.version.__version__"}
