
[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "picar-x"
authors = [
  { name="sunfounder", email="service@sunfounder.com" },
  { name="Tobin McD", email="138074176+tobinmcd@users.noreply.github.com" },
]
description = "Picar-X Projects"
readme = "README.md"
requires-python = ">=3.13"
keywords = ["picar-x", "sunfounder"]
dynamic = ["version"]

dependencies = [
    "fastapi[standard]>=0.121.2",
    "keyboard>=0.13.5",
    "uvicorn>=0.22.0",
]

[project.scripts]
picarx-serve = "gerg_driver.server:main"

[project.urls]
Repository = "https://github.com/sunfounder/picar-x"
Issues = "https://github.com/sunfounder/picar-x/issues"

[tool.setuptools]
packages = [
  "picarx",
  "gerg_driver",
]

[tool.setuptools.dynamic]
version = {attr = "picarx.version.__version__"}
